"""Execution backend protocol."""

from __future__ import annotations

from typing import Protocol

from wbcd_task1.execution.server.state_types import ArmState


class ExecutionBackend(Protocol):
    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def enable(self, arm: str | None = None) -> None: ...

    def stop(self, arm: str | None = None) -> None: ...

    def reset(self, arm: str | None = None) -> None: ...

    def go_home(self, arm: str | None = None) -> None: ...

    def get_state(self, arm: str | None = None) -> dict[str, ArmState]: ...

    def get_tcp_pose(self, arm: str) -> list[float]: ...

    def get_joints(self, arm: str) -> list[float]: ...

    def move_j(self, arm: str, joints: list[float], delta: bool = False) -> None: ...

    def move_p(self, arm: str, pose: list[float], delta: bool = False) -> None: ...

    def servo_delta_pose(self, arm: str, delta_pose: list[float]) -> None: ...

    def open_gripper(self, arm: str, width_m: float = 0.1, force: float = 1.0) -> None: ...

    def close_gripper(self, arm: str, width_m: float = 0.0, force: float = 1.0) -> None: ...
